backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "static/images/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "pages"
    label: "Strony"
    files:
      - label: "Strona główna"
        name: "homepage"
        file: "content/pages/homepage.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
      - label: "Oferta"
        name: "oferta"
        file: "content/pages/offer.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
      - label: "Cennik"
        name: "cennik"
        file: "content/pages/prices.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
      - label: "Transport"
        name: "transport"
        file: "content/pages/transport.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
      - label: "Mati-Trans"
        name: "mati-transport"
        file: "content/pages/mati-trans.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
      - label: "Kontakt"
        name: "kontakt"
        file: "content/pages/contact.md"
        fields:
          - {label: "Tytuł", name: title, widget: string, required: true}
          - {label: "Opis", name: description, widget: text, required: true}
          - {label: "Treść", name: body, widget: markdown}
